// Package sdk provides the Go SDK for writing WASM skills.
// Skills compile with: GOOS=wasip1 GOARCH=wasm go build -o dist/skill.wasm ./
package sdk

// Version is the protocol version. Must be incremented on breaking changes.
const Version = 1

// InvokeRequest represents an incoming skill invocation.
type InvokeRequest struct {
	Version      int    `msgpack:"version"`
	RequestID    string `msgpack:"request_id"`
	TraceID      string `msgpack:"trace_id"`
	SessionID    string `msgpack:"session_id"`
	LLMSessionID string `msgpack:"llm_session_id"`
	Method       string `msgpack:"method"`
	SkillID      string `msgpack:"skill_id"`
	CallerID     string `msgpack:"caller_id,omitempty"` // skill ID if called by another skill
	State        []byte `msgpack:"state"`
	Payload      []byte `msgpack:"payload"`
	DeadlineNs   int64  `msgpack:"deadline_ns"`
}

// InvokeResponse is returned by the skill's handle() function.
type InvokeResponse struct {
	Version  int       `msgpack:"version"`
	State    []byte    `msgpack:"state"`
	Payload  []byte    `msgpack:"payload"`
	Error    string    `msgpack:"error,omitempty"`
	Commands []Command `msgpack:"commands,omitempty"`
	// LLMContext is optional extra text sent to the LLM alongside the tool result.
	// Set via ctx.SetLLMContext("...") in the handler.
	// The host appends it to the MCP response as additional context.
	LLMContext string `msgpack:"llm_context,omitempty"`
}

// CommandType enumerates the command types the platform understands.
type CommandType string

const (
	CmdCallModule  CommandType = "call_module"
	CmdBatchInvoke CommandType = "batch_invoke"
	CmdSchedule    CommandType = "schedule"
	CmdEmitEvent   CommandType = "emit_event"
	CmdSubscribe   CommandType = "subscribe"
	CmdStoreKV     CommandType = "store_kv"
	CmdLoadKV      CommandType = "load_kv"
	CmdSpawn       CommandType = "spawn"
	CmdTerminate   CommandType = "terminate"
)

// Command is an instruction returned by the skill to the platform.
type Command struct {
	Type    CommandType            `msgpack:"type"`
	Payload map[string]interface{} `msgpack:"payload,omitempty"`
}

// BatchItem is one call inside a batch_invoke command.
type BatchItem struct {
	// Index is the caller-assigned position; preserved in BatchResult.Items.
	Index   int    `msgpack:"index"`
	SkillID string `msgpack:"skill_id"`
	Method  string `msgpack:"method"`
	// Payload is the msgpack-encoded arguments for the method.
	Payload []byte `msgpack:"payload"`
}

// BatchItemResult holds the outcome of one BatchItem after execution.
type BatchItemResult struct {
	Index   int    `msgpack:"index"`
	Payload []byte `msgpack:"payload,omitempty"`
	// Error is the skill-level error string, or "" on success.
	Error string `msgpack:"error,omitempty"`
}

// BatchResult is delivered to the callback method declared in batch_invoke.
type BatchResult struct {
	// BatchID is a unique ID for this batch execution (generated by the host).
	BatchID string            `msgpack:"batch_id"`
	Items   []BatchItemResult `msgpack:"items"`
}

// BatchInvokePayload is the payload map for a CmdBatchInvoke Command.
// Use BatchInvokeCommand() to construct it correctly.
type BatchInvokePayload struct {
	Items       []BatchItem `msgpack:"items"`
	Callback    string      `msgpack:"callback"`
	Concurrency int         `msgpack:"concurrency"` // 0 = unlimited
}

// BatchInvokeCommand builds a batch_invoke Command ready to include in
// InvokeResponse.Commands.
//
//	return sdk.InvokeResponse{
//	    Commands: []sdk.Command{
//	        sdk.BatchInvokeCommand([]sdk.BatchItem{
//	            {Index: 0, SkillID: "fs-skill", Method: "read", Payload: p0},
//	            {Index: 1, SkillID: "fs-skill", Method: "read", Payload: p1},
//	        }, "on_batch_result", 0),
//	    },
//	}
func BatchInvokeCommand(items []BatchItem, callback string, concurrency int) Command {
	// We need map[string]interface{} for the generic Command.Payload field.
	// Convert BatchItem slice to []interface{} of maps so the platform
	// can decode it from the generic command payload.
	rawItems := make([]interface{}, len(items))
	for i, it := range items {
		rawItems[i] = map[string]interface{}{
			"index":    it.Index,
			"skill_id": it.SkillID,
			"method":   it.Method,
			"payload":  it.Payload,
		}
	}
	return Command{
		Type: CmdBatchInvoke,
		Payload: map[string]interface{}{
			"items":       rawItems,
			"callback":    callback,
			"concurrency": concurrency,
		},
	}
}

// HistoryMessage is one entry from the dialogue history.
type HistoryMessage struct {
	Role    string `msgpack:"role"`
	Content string `msgpack:"content"`
}

// PromptRequest is sent to the host's prompt_complete ABI function.
type PromptRequest struct {
	Prompt      string  `msgpack:"prompt"`
	Temperature float64 `msgpack:"temperature"`
	MaxTokens   int     `msgpack:"max_tokens"`
}

// PromptResponse is returned from the host's prompt_complete ABI function.
type PromptResponse struct {
	Content string `msgpack:"content"`
	Error   string `msgpack:"error,omitempty"`
}
